Started logging messages at Mon Sep 21 11:56:07 2026
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: On
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 129 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 68
Info:            Created 
Info:        Working on 69
Info:            Created 
Info:        Working on 93
Info:            Created 
Info:        Working on 95
Info:            Created 
Info:        Working on 8
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 91
Info:            Created 
Info:        Working on 12
Info:            Created 
Info:        Working on 155
Info:            Created 
Info:        Working on 156
Info:            Created 
Info:        Working on 17
Info:            Created 
Info:        Working on 243
Info:            Created 
Info:        Working on 320
Info:            Created 
Info:        Working on 399
Info:            Created 
Info:        Working on 478
Info:            Created 
Info:        Working on 554
Info:            Created 
Info:        Working on 622
Info:            Created 
Info:        Working on 666
Info:            Created 
Info:        Working on 607
Info:            Created 
Info:        Working on 535
Info:            Created 
Info:        Working on 458
Info:            Created 
Info:        Working on 379
Info:            Created 
Info:        Working on 300
Info:            Created 
Info:        Working on 165
Info:            Created 
Info:        Working on 213
Info:            Created 
Info:        Working on 214
Info:            Created 
Info:        Working on 281
Info:            Created 
Info:        Working on 282
Info:            Created 
Info:        Working on 357
Info:            Created 
Info:        Working on 358
Info:            Created 
Info:        Working on 434
Info:            Created 
Info:        Working on 435
Info:            Created 
Info:        Working on 513
Info:            Created 
Info:        Working on 514
Info:            Created 
Info:        Working on 588
Info:            Created 
Info:        Working on 589
Info:            Created 
Info:        Working on 654
Info:            Created 
Info:        Working on 655
Info:            Created 
Info:        Working on 703
Info:            Created 
Info:        Working on 704
Info:            Created 
Info:        Working on 745
Info:            Created 
Info:        Working on 746
Info:            Created 
Info:        Working on 781
Info:            Created 
Info:        Working on 782
Info:            Created 
Info:        Working on 817
Info:            Created 
Info:        Working on 818
Info:            Created 
Info:        Working on 853
Info:            Created 
Info:        Working on 854
Info:            Created 
Info:        Working on 889
Info:            Created 
Info:        Working on 890
Info:            Created 
Info:        Working on 925
Info:            Created 
Info:        Working on 926
Info:            Created 
Info:        Working on 961
Info:            Created 
Info:        Working on 962
Info:            Created 
Info:        Working on 997
Info:            Created 
Info:        Working on 998
Info:            Created 
Info:        Working on 1033
Info:            Created 
Info:        Working on 1034
Info:            Created 
Info:        Working on 1069
Info:            Created 
Info:        Working on 1070
Info:            Created 
Info:        Working on 1105
Info:            Created 
Info:        Working on 1106
Info:            Created 
Info:        Working on 1141
Info:            Created 
Info:        Working on 1142
Info:            Created 
Info:        Working on 1177
Info:            Created 
Info:        Working on 1178
Info:            Created 
Info:        Working on 1213
Info:            Created 
Info:        Working on 1214
Info:            Created 
Info:        Working on 1249
Info:            Created 
Info:        Working on 1250
Info:            Created 
Info:        Working on 1285
Info:            Created 
Info:        Working on 1286
Info:            Created 
Info:        Working on 1321
Info:            Created 
Info:        Working on 1322
Info:            Created 
Info:        Working on 1357
Info:            Created 
Info:        Working on 1358
Info:            Created 
Info:        Working on 1393
Info:            Created 
Info:        Working on 1394
Info:            Created 
Info:        Working on 1429
Info:            Created 
Info:        Working on 1430
Info:            Created 
Info:        Working on 1465
Info:            Created 
Info:        Working on 1466
Info:            Created 
Info:        Working on 1501
Info:            Created 
Info:        Working on 1502
Info:            Created 
Info:        Working on 1537
Info:            Created 
Info:        Working on 1538
Info:            Created 
Info:        Working on 1573
Info:            Created 
Info:        Working on 1574
Info:            Created 
Info:        Working on 1609
Info:            Created 
Info:        Working on 1610
Info:            Created 
Info:        Working on 1645
Info:            Created 
Info:        Working on 1646
Info:            Created 
Info:        Working on 1681
Info:            Created 
Info:        Working on 1682
Info:            Created 
Info:        Working on 1717
Info:            Created 
Info:        Working on 1718
Info:            Created 
Info:        Working on 1753
Info:            Created 
Info:        Working on 1754
Info:            Created 
Info:        Working on 1789
Info:            Created 
Info:        Working on 1790
Info:            Created 
Info:        Working on 1825
Info:            Created 
Info:        Working on 1826
Info:            Created 
Info:        Working on 1861
Info:            Created 
Info:        Working on 1862
Info:            Created 
Info:        Working on 1897
Info:            Created 
Info:        Working on 1898
Info:            Created 
Info:        Working on 1933
Info:            Created 
Info:        Working on 1934
Info:            Created 
Info:        Working on 1969
Info:            Created 
Info:        Working on 1970
Info:            Created 
Info:        Working on 2005
Info:            Created 
Info:        Working on 2006
Info:            Created 
Info:        Working on 2041
Info:            Created 
Info:        Working on 2042
Info:            Created 
Info:        Working on 2077
Info:            Created 
Info:        Working on 2078
Info:            Created 
Info:        Working on 2113
Info:            Created 
Info:        Working on 2114
Info:            Created 
Info:        Working on 2149
Info:            Created 
Info:        Working on 2150
Info:            Created 
Info:        Working on 2185
Info:            Created 
Info:        Working on 2186
Info:            Created 
Info:        Working on 2221
Info:            Created 
Info:        Working on 2222
Info:            Created 
Info:        Working on 2257
Info:            Created 
Info:        Working on 2258
Info:            Created 
Info:        Working on 2293
Info:            Created 
Info:        Working on 2294
Info:            Created 
Info:        Working on 2329
Info:            Created 
Info:        Working on 2330
Info:            Created 
Info:        Working on 2365
Info:            Created 
Info:        Working on 2366
Info:            Created 
Info:        Working on 2401
Info:            Created 
Info:        Working on 2402
Info:            Created 
Info:        Working on 2437
Info:            Created 
Info:        Working on 2438
Info:            Created 
Info:        Working on 2473
Info:            Created 
Info:        Working on 2474
Info:            Created 
Info:        Working on 2509
Info:            Created 
Info:        Working on 2510
Info:            Created 
Info:        Working on 2545
Info:            Created 
Info:        Working on 2546
Info:            Created 
Info:        Working on 2581
Info:            Created 
Info:        Working on 2582
Info:            Created 
Info:        Working on 2617
Info:            Created 
Info:        Working on 2618
Info:            Created 
Info:        Working on 2653
Info:            Created 
Info:        Working on 2654
Info:            Created 
Info:        Working on 2689
Info:            Created 
Info:        Working on 2690
Info:            Created 
Info:        Working on 2725
Info:            Created 
Info:        Working on 2726
Info:            Created 
Info:        Working on 2761
Info:            Created 
Info:        Working on 2762
Info:            Created 
Info:        Working on 2797
Info:            Created 
Info:        Working on 2798
Info:            Created 
Info:        Working on 2833
Info:            Created 
Info:        Working on 2834
Info:            Created 
Info:        Working on 2869
Info:            Created 
Info:        Working on 2870
Info:            Created 
Info:        Working on 2905
Info:            Created 
Info:        Working on 2906
Info:            Created 
Info:        Working on 2941
Info:            Created 
Info:        Working on 2942
Info:            Created 
Info:        Working on 2977
Info:            Created 
Info:        Working on 2978
Info:            Created 
Info:        Working on 3013
Info:            Created 
Info:        Working on 3014
Info:            Created 
Info:        Working on 3049
Info:            Created 
Info:        Working on 3050
Info:            Created 
Info:        Working on 3085
Info:            Created 
Info:        Working on 3086
Info:            Created 
Info:        Working on 3121
Info:            Created 
Info:        Working on 3122
Info:            Created 
Info:        Working on 3157
Info:            Created 
Info:        Working on 3158
Info:            Created 
Info:        Working on 3193
Info:            Created 
Info:        Working on 3194
Info:            Created 
Info:        Working on 3229
Info:            Created 
Info:        Working on 3230
Info:            Created 
Info:        Working on 3265
Info:            Created 
Info:        Working on 3266
Info:            Created 
Info:        Working on 3301
Info:            Created 
Info:        Working on 3302
Info:            Created 
Info:        Working on 3337
Info:            Created 
Info:        Working on 3338
Info:            Created 
Info:        Working on 3373
Info:            Created 
Info:        Working on 3374
Info:            Created 
Info:        Working on 3409
Info:            Created 
Info:        Working on 3410
Info:            Created 
Info:        Working on 3445
Info:            Created 
Info:        Working on 3446
Info:            Created 
Info:        Working on 3481
Info:            Created 
Info:        Working on 3482
Info:            Created 
Info:        Working on 3517
Info:            Created 
Info:        Working on 3518
Info:            Created 
Info:        Working on 3553
Info:            Created 
Info:        Working on 3554
Info:            Created 
Info:        Working on 3589
Info:            Created 
Info:        Working on 3590
Info:            Created 
Info:        Working on 3625
Info:            Created 
Info:        Working on 3626
Info:            Created 
Info:        Working on 3661
Info:            Created 
Info:        Working on 3662
Info:            Created 
Info:        Working on 3697
Info:            Created 
Info:        Working on 3698
Info:            Created 
Info:        Working on 3733
Info:            Created 
Info:        Working on 3734
Info:            Created 
Info:        Working on 3769
Info:            Created 
Info:        Working on 3770
Info:            Created 
Info:        Working on 3805
Info:            Created 
Info:        Working on 3806
Info:            Created 
Info:        Working on 3841
Info:            Created 
Info:        Working on 3842
Info:            Created 
Info:        Working on 3877
Info:            Created 
Info:        Working on 3878
Info:            Created 
Info:        Working on 3913
Info:            Created 
Info:        Working on 3914
Info:            Created 
Info:        Working on 3949
Info:            Created 
Info:        Working on 3950
Info:            Created 
Info:        Working on 3985
Info:            Created 
Info:        Working on 3986
Info:            Created 
Info:        Working on 4021
Info:            Created 
Info:        Working on 4022
Info:            Created 
Info:        Working on 4057
Info:            Created 
Info:        Working on 4058
Info:            Created 
Info:        Working on 4093
Info:            Created 
Info:        Working on 4094
Info:            Created 
Info:        Working on 4129
Info:            Created 
Info:        Working on 4130
Info:            Created 
Info:        Working on 4165
Info:            Created 
Info:        Working on 4166
Info:            Created 
Info:        Working on 4201
Info:            Created 
Info:        Working on 4202
Info:            Created 
Info:        Working on 4237
Info:            Created 
Info:        Working on 4238
Info:            Created 
Info:        Working on 4272
Info:            Created 
Info:        Working on 4273
Info:            Created 
Info:        Working on 4305
Info:            Created 
Info:        Working on 4306
Info:            Created 
Info:        Working on 4334
Info:            Created 
Info:        Working on 4335
Info:            Created 
Info:        Working on 4352
Info:            Created 
Info:        Working on 4353
Info:            Created 
Info:        Working on 26
Info:            Created 
Info:        Working on 166
Info:            Created 
Info:        Working on 293
Info:            Created 
Info:        Working on 372
Info:            Created 
Info:        Working on 449
Info:            Created 
Info:        Working on 527
Info:            Created 
Info:        Working on 601
Info:            Created 
Info:        Working on 661
Info:            Created 
Info:        Working on 615
Info:            Created 
Info:        Working on 546
Info:            Created 
Info:        Working on 469
Info:            Created 
Info:        Working on 390
Info:            Created 
Info:        Working on 311
Info:            Created 
Info:        Working on 236
Info:            Created 
Info:        Working on 262
Info:            Created 
Info:        Working on 263
Info:            Created 
Info:        Working on 338
Info:            Created 
Info:        Working on 339
Info:            Created 
Info:        Working on 415
Info:            Created 
Info:        Working on 416
Info:            Created 
Info:        Working on 494
Info:            Created 
Info:        Working on 495
Info:            Created 
Info:        Working on 569
Info:            Created 
Info:        Working on 570
Info:            Created 
Info:        Working on 635
Info:            Created 
Info:        Working on 636
Info:            Created 
Info:        Working on 684
Info:            Created 
Info:        Working on 685
Info:            Created 
Info:        Working on 726
Info:            Created 
Info:        Working on 727
Info:            Created 
Info:        Working on 762
Info:            Created 
Info:        Working on 763
Info:            Created 
Info:        Working on 798
Info:            Created 
Info:        Working on 799
Info:            Created 
Info:        Working on 834
Info:            Created 
Info:        Working on 835
Info:            Created 
Info:        Working on 870
Info:            Created 
Info:        Working on 871
Info:            Created 
Info:        Working on 906
Info:            Created 
Info:        Working on 907
Info:            Created 
Info:        Working on 942
Info:            Created 
Info:        Working on 943
Info:            Created 
Info:        Working on 978
Info:            Created 
Info:        Working on 979
Info:            Created 
Info:        Working on 1014
Info:            Created 
Info:        Working on 1015
Info:            Created 
Info:        Working on 1050
Info:            Created 
Info:        Working on 1051
Info:            Created 
Info:        Working on 1086
Info:            Created 
Info:        Working on 1087
Info:            Created 
Info:        Working on 1122
Info:            Created 
Info:        Working on 1123
Info:            Created 
Info:        Working on 1158
Info:            Created 
Info:        Working on 1159
Info:            Created 
Info:        Working on 1194
Info:            Created 
Info:        Working on 1195
Info:            Created 
Info:        Working on 1230
Info:            Created 
Info:        Working on 1231
Info:            Created 
Info:        Working on 1266
Info:            Created 
Info:        Working on 1267
Info:            Created 
Info:        Working on 1302
Info:            Created 
Info:        Working on 1303
Info:            Created 
Info:        Working on 1338
Info:            Created 
Info:        Working on 1339
Info:            Created 
Info:        Working on 1374
Info:            Created 
Info:        Working on 1375
Info:            Created 
Info:        Working on 1410
Info:            Created 
Info:        Working on 1411
Info:            Created 
Info:        Working on 1446
Info:            Created 
Info:        Working on 1447
Info:            Created 
Info:        Working on 1482
Info:            Created 
Info:        Working on 1483
Info:            Created 
Info:        Working on 1518
Info:            Created 
Info:        Working on 1519
Info:            Created 
Info:        Working on 1554
Info:            Created 
Info:        Working on 1555
Info:            Created 
Info:        Working on 1590
Info:            Created 
Info:        Working on 1591
Info:            Created 
Info:        Working on 1626
Info:            Created 
Info:        Working on 1627
Info:            Created 
Info:        Working on 1662
Info:            Created 
Info:        Working on 1663
Info:            Created 
Info:        Working on 1698
Info:            Created 
Info:        Working on 1699
Info:            Created 
Info:        Working on 1734
Info:            Created 
Info:        Working on 1735
Info:            Created 
Info:        Working on 1770
Info:            Created 
Info:        Working on 1771
Info:            Created 
Info:        Working on 1806
Info:            Created 
Info:        Working on 1807
Info:            Created 
Info:        Working on 1842
Info:            Created 
Info:        Working on 1843
Info:            Created 
Info:        Working on 1878
Info:            Created 
Info:        Working on 1879
Info:            Created 
Info:        Working on 1914
Info:            Created 
Info:        Working on 1915
Info:            Created 
Info:        Working on 1950
Info:            Created 
Info:        Working on 1951
Info:            Created 
Info:        Working on 1986
Info:            Created 
Info:        Working on 1987
Info:            Created 
Info:        Working on 2022
Info:            Created 
Info:        Working on 2023
Info:            Created 
Info:        Working on 2058
Info:            Created 
Info:        Working on 2059
Info:            Created 
Info:        Working on 2094
Info:            Created 
Info:        Working on 2095
Info:            Created 
Info:        Working on 2130
Info:            Created 
Info:        Working on 2131
Info:            Created 
Info:        Working on 2166
Info:            Created 
Info:        Working on 2167
Info:            Created 
Info:        Working on 2202
Info:            Created 
Info:        Working on 2203
Info:            Created 
Info:        Working on 2238
Info:            Created 
Info:        Working on 2239
Info:            Created 
Info:        Working on 2274
Info:            Created 
Info:        Working on 2275
Info:            Created 
Info:        Working on 2310
Info:            Created 
Info:        Working on 2311
Info:            Created 
Info:        Working on 2346
Info:            Created 
Info:        Working on 2347
Info:            Created 
Info:        Working on 2382
Info:            Created 
Info:        Working on 2383
Info:            Created 
Info:        Working on 2418
Info:            Created 
Info:        Working on 2419
Info:            Created 
Info:        Working on 2454
Info:            Created 
Info:        Working on 2455
Info:            Created 
Info:        Working on 2490
Info:            Created 
Info:        Working on 2491
Info:            Created 
Info:        Working on 2526
Info:            Created 
Info:        Working on 2527
Info:            Created 
Info:        Working on 2562
Info:            Created 
Info:        Working on 2563
Info:            Created 
Info:        Working on 2598
Info:            Created 
Info:        Working on 2599
Info:            Created 
Info:        Working on 2634
Info:            Created 
Info:        Working on 2635
Info:            Created 
Info:        Working on 2670
Info:            Created 
Info:        Working on 2671
Info:            Created 
Info:        Working on 2706
Info:            Created 
Info:        Working on 2707
Info:            Created 
Info:        Working on 2742
Info:            Created 
Info:        Working on 2743
Info:            Created 
Info:        Working on 2778
Info:            Created 
Info:        Working on 2779
Info:            Created 
Info:        Working on 2814
Info:            Created 
Info:        Working on 2815
Info:            Created 
Info:        Working on 2850
Info:            Created 
Info:        Working on 2851
Info:            Created 
Info:        Working on 2886
Info:            Created 
Info:        Working on 2887
Info:            Created 
Info:        Working on 2922
Info:            Created 
Info:        Working on 2923
Info:            Created 
Info:        Working on 2958
Info:            Created 
Info:        Working on 2959
Info:            Created 
Info:        Working on 2994
Info:            Created 
Info:        Working on 2995
Info:            Created 
Info:        Working on 3030
Info:            Created 
Info:        Working on 3031
Info:            Created 
Info:        Working on 3066
Info:            Created 
Info:        Working on 3067
Info:            Created 
Info:        Working on 3102
Info:            Created 
Info:        Working on 3103
Info:            Created 
Info:        Working on 3138
Info:            Created 
Info:        Working on 3139
Info:            Created 
Info:        Working on 3174
Info:            Created 
Info:        Working on 3175
Info:            Created 
Info:        Working on 3210
Info:            Created 
Info:        Working on 3211
Info:            Created 
Info:        Working on 3246
Info:            Created 
Info:        Working on 3247
Info:            Created 
Info:        Working on 3282
Info:            Created 
Info:        Working on 3283
Info:            Created 
Info:        Working on 3318
Info:            Created 
Info:        Working on 3319
Info:            Created 
Info:        Working on 3354
Info:            Created 
Info:        Working on 3355
Info:            Created 
Info:        Working on 3390
Info:            Created 
Info:        Working on 3391
Info:            Created 
Info:        Working on 3426
Info:            Created 
Info:        Working on 3427
Info:            Created 
Info:        Working on 3462
Info:            Created 
Info:        Working on 3463
Info:            Created 
Info:        Working on 3498
Info:            Created 
Info:        Working on 3499
Info:            Created 
Info:        Working on 3534
Info:            Created 
Info:        Working on 3535
Info:            Created 
Info:        Working on 3570
Info:            Created 
Info:        Working on 3571
Info:            Created 
Info:        Working on 3606
Info:            Created 
Info:        Working on 3607
Info:            Created 
Info:        Working on 3642
Info:            Created 
Info:        Working on 3643
Info:            Created 
Info:        Working on 3678
Info:            Created 
Info:        Working on 3679
Info:            Created 
Info:        Working on 3714
Info:            Created 
Info:        Working on 3715
Info:            Created 
Info:        Working on 3750
Info:            Created 
Info:        Working on 3751
Info:            Created 
Info:        Working on 3786
Info:            Created 
Info:        Working on 3787
Info:            Created 
Info:        Working on 3822
Info:            Created 
Info:        Working on 3823
Info:            Created 
Info:        Working on 3858
Info:            Created 
Info:        Working on 3859
Info:            Created 
Info:        Working on 3894
Info:            Created 
Info:        Working on 3895
Info:            Created 
Info:        Working on 3930
Info:            Created 
Info:        Working on 3931
Info:            Created 
Info:        Working on 3966
Info:            Created 
Info:        Working on 3967
Info:            Created 
Info:        Working on 4002
Info:            Created 
Info:        Working on 4003
Info:            Created 
Info:        Working on 4038
Info:            Created 
Info:        Working on 4039
Info:            Created 
Info:        Working on 4074
Info:            Created 
Info:        Working on 4075
Info:            Created 
Info:        Working on 4110
Info:            Created 
Info:        Working on 4111
Info:            Created 
Info:        Working on 4146
Info:            Created 
Info:        Working on 4147
Info:            Created 
Info:        Working on 4182
Info:            Created 
Info:        Working on 4183
Info:            Created 
Info:        Working on 4218
Info:            Created 
Info:        Working on 4219
Info:            Created 
Info:        Working on 4254
Info:            Created 
Info:        Working on 4255
Info:            Created 
Info:        Working on 4288
Info:            Created 
Info:        Working on 4289
Info:            Created 
Info:        Working on 4320
Info:            Created 
Info:        Working on 4321
Info:            Created 
Info:        Working on 4346
Info:            Created 
Info:        Working on 4347
Info:            Created 
Info:        Working on 4358
Info:            Created 
Info:        Working on 4359
Info:            Created 
Info:        Working on 44
Info:            Created 
Info:        Working on 72
Info:            Created 
Info:        Working on 99
Info:            Created 
Info:        Working on 134
Info:            Created 
Info:        Working on 183
Info:            Created 
Info:        Working on 247
Info:            Created 
Info:        Working on 323
Info:            Created 
Info:        Working on 402
Info:            Created 
Info:        Working on 481
Info:            Created 
Info:        Working on 556
Info:            Created 
Info:        Working on 619
Info:            Created 
Info:        Working on 665
Info:            Created 
Info:        Working on 671
Info:            Created 
Info:        Working on 711
Info:            Created 
Info:        Working on 713
Info:            Created 
Info:        Working on 285
Info:            Created 
Info:        Working on 361
Info:            Created 
Info:        Working on 438
Info:            Created 
Info:        Working on 517
Info:            Created 
Info:        Working on 592
Info:            Created 
Info:        Working on 658
Info:            Created 
Info:        Working on 707
Info:            Created 
Info:        Working on 749
Info:            Created 
Info:        Working on 785
Info:            Created 
Info:        Working on 821
Info:            Created 
Info:        Working on 857
Info:            Created 
Info:        Working on 893
Info:            Created 
Info:        Working on 929
Info:            Created 
Info:        Working on 965
Info:            Created 
Info:        Working on 1001
Info:            Created 
Info:        Working on 1037
Info:            Created 
Info:        Working on 1073
Info:            Created 
Info:        Working on 1109
Info:            Created 
Info:        Working on 1145
Info:            Created 
Info:        Working on 1181
Info:            Created 
Info:        Working on 1217
Info:            Created 
Info:        Working on 1253
Info:            Created 
Info:        Working on 1289
Info:            Created 
Info:        Working on 1325
Info:            Created 
Info:        Working on 1361
Info:            Created 
Info:        Working on 1397
Info:            Created 
Info:        Working on 1433
Info:            Created 
Info:        Working on 1469
Info:            Created 
Info:        Working on 1505
Info:            Created 
Info:        Working on 1541
Info:            Created 
Info:        Working on 1577
Info:            Created 
Info:        Working on 1613
Info:            Created 
Info:        Working on 1649
Info:            Created 
Info:        Working on 1685
Info:            Created 
Info:        Working on 1721
Info:            Created 
Info:        Working on 1757
Info:            Created 
Info:        Working on 1793
Info:            Created 
Info:        Working on 1829
Info:            Created 
Info:        Working on 1865
Info:            Created 
Info:        Working on 1901
Info:            Created 
Info:        Working on 1937
Info:            Created 
Info:        Working on 1973
Info:            Created 
Info:        Working on 2009
Info:            Created 
Info:        Working on 2045
Info:            Created 
Info:        Working on 2081
Info:            Created 
Info:        Working on 2117
Info:            Created 
Info:        Working on 2153
Info:            Created 
Info:        Working on 2189
Info:            Created 
Info:        Working on 2225
Info:            Created 
Info:        Working on 2261
Info:            Created 
Info:        Working on 2297
Info:            Created 
Info:        Working on 2333
Info:            Created 
Info:        Working on 2369
Info:            Created 
Info:        Working on 2405
Info:            Created 
Info:        Working on 2441
Info:            Created 
Info:        Working on 2477
Info:            Created 
Info:        Working on 2513
Info:            Created 
Info:        Working on 2549
Info:            Created 
Info:        Working on 2585
Info:            Created 
Info:        Working on 2621
Info:            Created 
Info:        Working on 2657
Info:            Created 
Info:        Working on 2693
Info:            Created 
Info:        Working on 2729
Info:            Created 
Info:        Working on 2765
Info:            Created 
Info:        Working on 2801
Info:            Created 
Info:        Working on 2837
Info:            Created 
Info:        Working on 2873
Info:            Created 
Info:        Working on 2909
Info:            Created 
Info:        Working on 2945
Info:            Created 
Info:        Working on 2981
Info:            Created 
Info:        Working on 3017
Info:            Created 
Info:        Working on 3053
Info:            Created 
Info:        Working on 3089
Info:            Created 
Info:        Working on 3125
Info:            Created 
Info:        Working on 3161
Info:            Created 
Info:        Working on 3197
Info:            Created 
Info:        Working on 3233
Info:            Created 
Info:        Working on 3269
Info:            Created 
Info:        Working on 3305
Info:            Created 
Info:        Working on 3341
Info:            Created 
Info:        Working on 3377
Info:            Created 
Info:        Working on 3413
Info:            Created 
Info:        Working on 3449
Info:            Created 
Info:        Working on 3485
Info:            Created 
Info:        Working on 3521
Info:            Created 
Info:        Working on 3557
Info:            Created 
Info:        Working on 3593
Info:            Created 
Info:        Working on 3629
Info:            Created 
Info:        Working on 3665
Info:            Created 
Info:        Working on 3701
Info:            Created 
Info:        Working on 3737
Info:            Created 
Info:        Working on 3773
Info:            Created 
Info:        Working on 3809
Info:            Created 
Info:        Working on 3845
Info:            Created 
Info:        Working on 3881
Info:            Created 
Info:        Working on 3917
Info:            Created 
Info:        Working on 3953
Info:            Created 
Info:        Working on 3989
Info:            Created 
Info:        Working on 4025
Info:            Created 
Info:        Working on 4061
Info:            Created 
Info:        Working on 4097
Info:            Created 
Info:        Working on 4133
Info:            Created 
Info:        Working on 4169
Info:            Created 
Info:        Working on 4205
Info:            Created 
Info:        Working on 4241
Info:            Created 
Info:        Working on 4276
Info:            Created 
Info:        Working on 4309
Info:            Created 
Info:        Working on 4338
Info:            Created 
Info:        Working on 4356
Info:            Created 
Info:        Working on 4362
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 3.88602e-06
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Mon Sep 21 11:56:07 2026
